config/routes.rb
Rails.application.routes.draw do
# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
  end

# 会員用
# URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  scope module: :public do
    root 'homes#top'
    get 'about'=>'homes#about' ,as:'about'

    get 'users/mypage/:id' => 'users#show', as: 'mypage'

    # users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'users/information/edit/:id' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'

    resources :catches, only: [:index,:show,:edit,:create,:destroy,:update] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    devise_scope :user do
      post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
    end
  end

end

app/views/layouts/_header.html.erb
<header class="<%= (admin_signed_in? ? "admin_header" : "" ) %>">
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">

    <%= link_to 'FishingSns', (admin_signed_in? ? admin_top_path : root_path ), class: "navbar-brand text-light" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <!--管理者ログイン時の処理-->
        <% if admin_signed_in? %>
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <!--<li class="nav-item dropdown">-->
          <!--  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
          <!--    Dropdown-->
          <!--  </a>-->
          <!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
          <!--    <a class="dropdown-item" href="#">Action</a>-->
          <!--    <a class="dropdown-item" href="#">Another action</a>-->
          <!--    <div class="dropdown-divider"></div>-->
          <!--    <a class="dropdown-item" href="#">Something else here</a>-->
          <!--  </div>-->
          <!--</li>-->
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>

        <!--ユーザーログイン時の処理-->
        <% elsif user_signed_in? %>
          <li class="nav-item">
            <%= link_to mypage_path(current_user),class: 'nav-link text-light' do %>
              <i class="fab fa-octopus-deploy"></i> MyPage
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to catches_path,class: 'nav-link text-light' do %>
            <i class="fas fa-fish"></i> Catch
            <% end %>
          </li>
          <!--<li class="nav-item dropdown ">-->
          <!--  <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
          <!--    Dropdown-->
          <!--  </a>-->
          <!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
          <!--    <a class="dropdown-item" href="#">Action</a>-->
          <!--    <a class="dropdown-item" href="#">Another action</a>-->
          <!--    <div class="dropdown-divider"></div>-->
          <!--    <a class="dropdown-item" href="#">Something else here</a>-->
          <!--  </div>-->
          <!--</li>-->
          <li class="nav-item">
            <%= link_to destroy_user_session_path,method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log_out
            <% end %>
          </li>

        <!--ログインしていない場合の処理-->
        <% else %>
          <li class="nav-item active">
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> About
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign_up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log_in
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to users_guest_sign_in_path,class: 'nav-link text-light', method: :post  do %>
              <i class="fas fa-user-alt"></i> Guest_Log_in
            <% end %>
          </li>
        <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FishingSns</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/163b8cc948.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>